

home_page = 'index.html'
registration_page = 'register.html'
setting_page = 'settings_user.html'
setting_redirect_page = 'settings_user'
user_profile  = 'red.html'
article_page    ='blog.html'
article_redirect='blog'
article_users_page='cm.html'
message_page='message.html'
chat_page = 'sms.html'
user_like_page='user_like.html'
change_page='change.html'
change_redirect='settings_user'
add_blog='addblog.html'
replay_page='replay.html'