# Generated by Django 5.0.7 on 2024-07-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_message_chat_remove_message_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssuser',
            name='read_sms',
            field=models.BooleanField(default=False),
        ),
    ]
